name: "WorkFlows Demo"

on: 
  push:
    branches: [ master ]

env:  
  NetCore_Version:  '3.1.x'

jobs:
  build:
    name: build and Deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    # - name: Setup Dotnet SDK
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: ${{ env.NetCore_Version }}
    - name: Restore
      shell: cmd
      run: dotnet restore
    - name: Build
      shell: cmd
      run:  dotnet build --no-restore -c Release
    # - name: Delete Existing Files
    #   shell: cmd
    #   run: | 
    #       Del E:\Akshay\Projects\Publish\*   
    - name: Publish
      shell: cmd 
      run:  dotnet publish --no-build -c Release -o E:\Akshay\Projects\Publish
    - name: IIS Deploy
      run: |
        Stop-IISSite -Name "Default Web Site"
 
    # - name: Publish Artifact
    #   uses: actions/upload-artifact@v1.0.0
    #   with: 
    #     name: webapp
    #     path: ./published    
    