name: "WorkFlows Demo"

on: 
  push:
    branches: [ master ]

env:  
  NetCore_Version:  '3.1.x'

jobs:
  build:
    name: build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run:  dotnet publish --no-build -c Release -o ./published

    - name: Publish Artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: webapp
        path: ./published      