name: "WorkFlows Demo"

on: 
  push:
    branches: [ master ]

env:  
  NetCore_Version:  '3.1.x'

jobs:
  build:
    name: build and Deploy
    runs-on: MX-Self-Hosted
    # runs-on: windows-2019
    steps:
    # - uses: actions/checkout@v1
    # # - name: Setup Dotnet SDK
    # #   uses: actions/setup-dotnet@v1
    # #   with:
    # #     dotnet-version: ${{ env.NetCore_Version }}
    # - name: Restore
    #   shell: cmd
    #   run: dotnet restore
    # - name: Build
    #   shell: cmd
    #   run:  dotnet build --no-restore -c Release
    # - name: Delete Existing Files
    #   shell: cmd
    #   run:  E:\Akshay\Projects\test.bat
      # run: | 
      #     powershell.exe -ExecutionPolicy Bypass -NoProfile -NoExit -File E:\Akshay\Projects\main.ps1   
      #     powershell -Command "Start-Process powershell \"-ExecutionPolicy Bypass -NoProfile -NoExit -Command `\"cd \`\"%E:\Akshay\Projects%`\"; & \`\".\%main.ps1%\`\"`\"\" -Verb RunAs"
   
   
    # - name: Publish
    #   shell: cmd 
    #   run:  dotnet publish --no-build -c Release -o E:\Akshay\Projects\Publish
    #   # run: dotnet publish --no-build -c Release -o ./published
    - name: publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pub
        path: E:\Akshay\Projects\publishDemo
  
  deploy:
    needs:  [build]
    runs-on: EC2Runner
    steps:
      - name: 
        uses: actions/download-artifact@v3.0.0
        with:
          name: pub
          path: C:\inetpub\GitFiles
      # - name: FTP Deploy
      #   uses: sebastianpopp/ftp-action@v2.0.0
      #   with:
      #     # ftp server
      #     host: ${{ secrets.UAT_IP }}
      #     # ftp username
      #     user: ${{ secrets.USERNAME }}
      #     # ftp password
      #     password: ${{ secrets.PASSWORD }}
      #     # Folder to upload from, must end with trailing slash /
      #     localDir: E:/Akshay/Projects/publishDemo/
      #     # Path to upload to on the server. Must end with trailing slash /
      #     remoteDir: C:/inetpub/wwwroot/

    # - name: copy file via ssh password
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.UAT_IP}}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: 22
    #     source: "./published/*"
    #     target: E:\Akshay\Projects\Publish

    # - name: IIS Deploy
    #   run: |
    #     Stop-IISSite -Name "Default Web Site"
  
    # - name: Publish Artifact
    #   uses: actions/upload-artifact@v1.0.0
    #   with: 
    #     name: webapp
    #     path: ./published    
    